var area = {
    N: [
        {
            city: "台北",
            name: "展望動物醫院",
            phone: "02 2388 0122",
            address: "台北市萬華區中華路二段二號",
            epidemic: true,
        },
        {
            city: "台北",
            name: "大安動物醫院",
            phone: "02 2363 2020",
            address: "台北市中正區羅斯福路四段162號1樓",
            epidemic: true,
        },
        {
            city: "台北",
            name: "伊甸動物醫院",
            phone: "02 8509 2579",
            address: "台北市中山區北安路554巷33號",
            epidemic: true,
        },
        {
            city: "台北",
            name: "阿牛犬貓急診醫院",
            phone: "02 2882 7381",
            address: "台北市士林區基河路238號",
            epidemic: true,
        },
        {
            city: "台北",
            name: "慈愛24小時動物醫院",
            phone: "02 2556 3320",
            address: "台北市大同區寧夏路1號",
            epidemic: true,
        },
        {
            city: "台北",
            name: "太僕動物醫院",
            phone: "02 2517 0902",
            address: "台北市中山區龍江路260號",
            epidemic: true,
        },
        {
            city: "台北",
            name: "南京太僕動物醫院",
            phone: "02 2756 2005",
            address: "台北市松山區南京東路五段286號",
            epidemic: true,
        },
        {
            city: "台北",
            name: "布達羊急診動物醫院",
            phone: "02 2834 1119",
            address: "台北市士林區忠誠路102號",
            epidemic: true,
        },
        {
            city: "台北",
            name: "全民動物醫院",
            phone: "02 2893 9752",
            address: "台北市北投區懷德街6-3號",
            epidemic: true,
        },
        {
            city: "台北",
            name: "全國24小時動物醫院",
            phone: "02 8791 8706",
            address: "台北市內湖區舊宗路一段30巷13號",
            epidemic: true,
        },
        {
            city: "台北",
            name: "大群動物醫院",
            phone: "02 2930 5557",
            address: "台北市文山區羅斯福路六段206號",
            epidemic: true,
        },
        {
            city: "台北",
            name: "仁慈動物醫院",
            phone: "02 2533 6983、急診：0935 578 571",
            address: "台北市中山區北安路518巷6號1樓",
            epidemic: false,
        },
        {
            city: "台北",
            name: "漢民動物醫院",
            phone: "02 2307 4801",
            address: "台北市和平西路一段156號",
            epidemic: false,
        },
        {
            city: "台北",
            name: "全民動物醫院",
            phone: "02 2553 0371",
            address: "台北市大同區民生西路247號、249號",
            epidemic: false,
        },
        {
            city: "台北",
            name: "隆記動物醫院",
            phone: "02 2760 7639、02 2746 6888",
            address: "台北市民生東路五段63號",
            epidemic: false,
        },
        {
            city: "台北",
            name: "嘉慶動物醫院",
            phone: "02 8787 9121",
            address: "台北市松山區八德路四緞218號1樓",
            epidemic: false,
        },
        {
            city: "台北",
            name: "幸福動物醫院",
            phone: "02 2700 5277、急診：02 2700 5233",
            address: "台北市大安區延吉街251號1樓",
            epidemic: false,
        },
        {
            city: "台北",
            name: "藍天家畜醫院",
            phone: "02 2838 0088",
            address: "台北市士林區文林路759號",
            epidemic: false,
        },
        {
            city: "台北",
            name: "丹堤動物醫院",
            phone: "02 5586 5668",
            address: "台北市北投區知行路 208~2 號 1 樓",
            epidemic: false,
        },
        {
            city: "台北",
            name: "全安動物醫院",
            phone: "02 2633 6495",
            address: "台北市內湖區東湖路113巷54號",
            epidemic: false,
        },
        {
            city: "台北",
            name: "永春動物醫院",
            phone: "02 8789 8849",
            address: "台北市信義區忠孝東路五段424號",
            epidemic: false,
        },
        {
            city: "新北",
            name: "中日動物醫院",
            phone: "02 2226 3639",
            address: "新北市中和區中山路三段2號",
            epidemic: true,
        },
        {
            city: "新北",
            name: "牧村動物醫院",
            phone: "02 8951 1172~3",
            address: "板橋區民生路2段50號",
            epidemic: false,
        },
        {
            city: "新北",
            name: "哲生動物醫院",
            phone: "02 2809 2293、急診：0938 802 831",
            address: "新北市淡水區民族路29巷40號",
            epidemic: false,
        },
        {
            city: "新北",
            name: "提姆沃克醫院",
            phone: "02 8982 9291",
            address: "新北市三重區中正北路23號",
            epidemic: false,
        },
        {
            city: "新北",
            name: "來來動物醫院",
            phone: "02 8953 9739、急診：0910 035 175",
            address: "新北市中和區德光路29號",
            epidemic: false,
        },
        {
            city: "新北",
            name: "祐全動物醫院",
            phone: "02 2997 5827",
            address: "新北市新莊區幸福路795號",
            epidemic: false,
        },
        {
            city: "新北",
            name: "亞東動物醫院",
            phone: "(02)2221-8515 急診專線：0952-605051",
            address: "新北市中和區中正路639號",
            epidemic: false,
        },
        {
            city: "桃園",
            name: "品湛動物醫院",
            phone: "03 336 3252",
            address: "桃園市桃園區民生路495-9號",
            epidemic: true,
        },
        {
            city: "桃園",
            name: "磨鼻子動物醫院",
            phone: "03 453 5740",
            address: "桃園市中壢區延平路20號",
            epidemic: true,
        },
        {
            city: "桃園",
            name: "元氣動物醫院",
            phone: "03 355 3911",
            address: "桃園市莊敬路一段159號",
            epidemic: true,
        },
        {
            city: "桃園",
            name: "南崁動物醫院",
            phone: "03 352 0136",
            address: "桃園市蘆竹區中正路379號",
            epidemic: false,
        },
        {
            city: "桃園",
            name: "達特馬動物醫院",
            phone: "03 228 8884",
            address: "桃園市國際路一段1172號",
            epidemic: false,
        },
        {
            city: "新竹",
            name: "大福小幸動物醫院",
            phone: "03 530 0175",
            address: "新竹市香山區經國路三段92巷6號",
            epidemic: false,
        },
        {
            city: "新竹",
            name: "築心動物醫院",
            phone: "03 533 8055",
            address: "新竹市東區經國路一段654號",
            epidemic: false,
        },
        {
            city: "新竹",
            name: "中日動物醫院",
            phone: "03 523 1015",
            address: "新竹市西大路656號",
            epidemic: false,
        },
        {
            city: "新竹",
            name: "毛毛村動物醫院",
            phone: "03 562 0606",
            address: "新竹市東區南大路79-2號",
            epidemic: false,
        },
    ],
    W: [
        {
            city: "台中",
            name: "全國24小時動物醫院",
            phone: "04 2371 0496",
            address: "台中市西區五權八街100號",
            epidemic: true,
        },
        {
            city: "台中",
            name: "慈愛24小時動物醫院",
            phone: "04 2406 6688",
            address: "台中市大里區國光路二段539號",
            epidemic: true,
        },
        {
            city: "台中",
            name: "康德動物醫院",
            phone: "04 2241 2700",
            address: "台中市北屯區崇德路二段270號",
            epidemic: true,
        },
        {
            city: "台中",
            name: "成大動物醫院",
            phone: "04 2639 8365、急診：0908 198 108",
            address: "台中市清水區臨港路五段658巷27號",
            epidemic: true,
        },
        {
            city: "台中",
            name: "祥億動物醫院",
            phone: "04 2260 6450",
            address: "台中市南區復興路一段259號",
            epidemic: false,
        },
        {
            city: "台中",
            name: "羅大宇動物醫院",
            phone: "04 2372 8378",
            address: "台中市西區存中街153號",
            epidemic: false,
        },
        {
            city: "台中",
            name: "沐恩動物醫院",
            phone: "04 2207 7271",
            address: "台中市北區健行路865號",
            epidemic: false,
        },
        {
            city: "台中",
            name: "非凡動物醫院",
            phone: "04 2277 1269",
            address: "台中市太平區鵬儀路1-4號",
            epidemic: false,
        },
        {
            city: "台中",
            name: "宏仁動物醫院",
            phone: "04 2622 1278",
            address: "台中市清水區中華路442巷7號",
            epidemic: false,
        },
        {
            city: "台中",
            name: "格林威治動物醫院",
            phone: "04 2320 2279、04 2320 2379",
            address: "台中市南屯區文心路一段486號",
            epidemic: true,
        },
        {
            city: "彰化",
            name: "忠愛動物醫院",
            phone: "04 833 5520",
            address: "彰化縣員林市中山路二段490號",
            epidemic: false,
        },
        {
            city: "彰化",
            name: "快樂動物醫院",
            phone: "04 738 4978",
            address: "彰化市彰南路二段180號",
            epidemic: false,
        },
        {
            city: "彰化",
            name: "吉美動物醫院",
            phone: "04 872 2982",
            address: "彰化縣社頭鄉民生路750號",
            epidemic: false,
        },
        {
            city: "雲林",
            name: "弘安動物醫院",
            phone: "05 533 3536",
            address: "雲林縣斗六市西平路276號",
            epidemic: false,
        },
        {
            city: "雲林",
            name: "和牧動物醫院",
            phone: "05 633 0811",
            address: "雲林縣虎尾鎮光復路454號",
            epidemic: false,
        },
    ],
    S: [
        {
            city: "嘉義",
            name: "民族24小時動物醫院",
            phone: "05 228 9595",
            address: "嘉義市民族路776號",
            epidemic: false,
        },
        {
            city: "台南",
            name: "慈愛動物醫院",
            phone: "06 220 3166",
            address: "台南市西門路一段473號",
            epidemic: true,
        },
        {
            city: "台南",
            name: "全國動物醫院 台南分院",
            phone: "06 267 3191",
            address: "台南市東區崇德路620號2樓",
            epidemic: false,
        },
        {
            city: "台南",
            name: "中美獸醫院",
            phone: "06 281 2233",
            address: "台南市北區和緯路二段231號",
            epidemic: false,
        },
        {
            city: "高雄",
            name: "冠安動物醫院",
            phone: "07 223 6451",
            address: "高雄市苓雅區中正二路131-1號",
            epidemic: true,
        },
        {
            city: "高雄",
            name: "宏力動物醫院",
            phone: "07 310 2819",
            address: "高雄市三民區明誠一路326號",
            epidemic: true,
        },
        {
            city: "高雄",
            name: "梅西動物醫院 （營業到凌晨兩點）",
            phone: "07 345 2541",
            address: "高雄市左營區文府路498號",
            epidemic: false,
        },
        {
            city: "高雄",
            name: "杜莉德動物醫院",
            phone: "07 223 1295 急診：0989 682 888",
            address: "高雄市新興區和平一路295號",
            epidemic: false,
        },
        {
            city: "高雄",
            name: "中興動物大豐總院",
            phone: "07 384 4631",
            address: "高雄市三民區大豐二路118-1號",
            epidemic: false,
        },
        {
            city: "高雄",
            name: "希望動物醫院",
            phone: "07 753 7300 急診：0988 629 973",
            address: "高雄市鳳山區凱旋路凱旋路100號",
            epidemic: false,
        },
        {
            city: "高雄",
            name: "烏鐸動物醫院",
            phone: "07 722 0804",
            address: "高雄市苓雅區中正一路139號",
            epidemic: false,
        },
        {
            city: "高雄",
            name: "聯盟動物醫院",
            phone: "07 3740964",
            address: "高雄市仁武區鳳仁路231號",
            epidemic: false,
        },
        {
            city: "屏東",
            name: "大同動物醫院",
            phone: "08 733 9215",
            address: "屏東市民族路222號",
            epidemic: false,
        },
        {
            city: "屏東",
            name: "毛小孩24小時動物醫院",
            phone: "08 751 2022",
            address: "屏東市仁愛路7號",
            epidemic: false,
        },
    ],
    E: [
        {
            city: "花蓮",
            name: "中原動物醫院",
            phone: "03 834 1857",
            address: "花蓮縣花蓮市中山路438號",
            epidemic: false,
        },
        {
            city: "花蓮",
            name: "上海動物醫院",
            phone: "03 834 1853",
            address: "花蓮縣花蓮市上海街63號",
            epidemic: false,
        },
    ],
};